version: '3.8'

services:
  restomrp-db:
    image: postgres:15-alpine
    container_name: restomrp_postgres
    restart: always
    environment:
      POSTGRES_USER: mrp_admin
      POSTGRES_PASSWORD: mrp_password_123
      POSTGRES_DB: restomrp_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mrp-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: restomrp_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mrp.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - restomrp-db
    networks:
      - mrp-network

volumes:
  pgdata: # Lưu trữ dữ liệu vĩnh viễn, không bị mất khi tắt Docker

networks:
  mrp-network:
    driver: bridge